services:

  backend:
    image: birender2026/ml-hub-backend:1.0.0
    container_name: ml-hub-backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_NAME: mlhub
      DB_USER: root
      DB_PASSWORD: 1234
      OMDB_API_KEY: dd0b5093
    restart: unless-stopped

  frontend:
    image: birender2026/ml-hub-frontend:1.0.0
    container_name: ml-hub-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped